<?php

declare(strict_types=1);

namespace Relaticle\Documentation\Http\Controllers;

use Illuminate\View\View;
use Relaticle\Documentation\Support\DocPage;
use Relaticle\Documentation\Support\DocsNavigation;
use Relaticle\Documentation\Support\DocsRepository;
use Relaticle\Documentation\Support\HeadingAnchors;
use Relaticle\Documentation\Support\RenderDocMarkdown;

final readonly class DocumentationController
{
    /**
     * The five guides live flat at /docs/{type} with no category segment in
     * the URL, but DocsRepository's content contract is always
     * {area}/{category}/{slug} -- "guides" is that one fixed category. The
     * sixth entry on the index, the API reference, is generated by Scribe at
     * this same /docs/api URL and has no markdown file (see
     * config('documentation.api_reference')).
     */
    private const string CATEGORY = 'docs/guides';

    public function __construct(
        private DocsRepository $repository,
        private RenderDocMarkdown $renderMarkdown,
        private DocsNavigation $navigation,
        private HeadingAnchors $headingAnchors,
    ) {}

    public function index(): View
    {
        return view('documentation::docs.hub', [
            'nav' => ($this->navigation)(),
        ]);
    }

    public function show(string $type): View
    {
        $page = $this->repository->find(self::CATEGORY."/{$type}");

        abort_unless($page instanceof DocPage, 404);

        $pages = $this->repository->pagesIn(self::CATEGORY)->values();

        $currentIndex = $pages->search(
            fn (DocPage $candidate): bool => $candidate->path === $page->path,
        );

        return view('documentation::docs.article', [
            'page' => $page,
            'body' => ($this->renderMarkdown)($page->body),
            'headings' => $this->headingAnchors->headings($page->body),
            'previous' => $currentIndex !== false && $currentIndex > 0 ? $pages->get($currentIndex - 1) : null,
            'next' => $currentIndex !== false && $currentIndex < $pages->count() - 1 ? $pages->get($currentIndex + 1) : null,
            'nav' => ($this->navigation)(),
            'currentPath' => $page->path,
        ]);
    }
}
