name: Task or improvement
description: Propose a specific task, refactoring, or technical improvement
labels: ["area:dev"]
projects: ["Relaticle/1"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for proposing specific technical tasks, refactorings, or improvements.

        For feature ideas or general suggestions, please use [Discussions → Ideas](https://github.com/Relaticle/relaticle/discussions/new?category=ideas) instead.

  - type: input
    id: area
    attributes:
      label: Area
      description: Which area of the codebase does this relate to?
      placeholder: "e.g., Import Wizard, Custom Fields, API, UI, Database, Authentication"

  - type: textarea
    id: description
    attributes:
      label: Task description
      description: What needs to be done?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why should this be done? What problem does it solve or what value does it add?
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: How will we know when this task is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Tests added/updated

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other relevant information, code references, or related issues
