<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Content Path
    |--------------------------------------------------------------------------
    |
    | Root directory for the markdown-driven content engine (DocsRepository).
    | Every file lives at {content_path}/{area}/{category}/{slug}.md, e.g.
    | help/getting-started/create-your-first-company.md. A category's own
    | metadata lives in that directory's _index.md.
    |
    */
    'content_path' => base_path('packages/Documentation/resources/content'),

    /*
    |--------------------------------------------------------------------------
    | Cache Settings
    |--------------------------------------------------------------------------
    |
    | Gates DocsRepository's content manifest (alongside app.debug, which
    | always bypasses it) — flip DOCUMENTATION_CACHE_ENABLED off to force a
    | rebuild without touching a file. The manifest cache invalidates by
    | comparing a content-hash signature on every read, not by expiry, so
    | there is no separate ttl to configure.
    |
    */
    'cache' => [
        'enabled' => env('DOCUMENTATION_CACHE_ENABLED', true),
    ],

    /*
    |--------------------------------------------------------------------------
    | API Reference Link
    |--------------------------------------------------------------------------
    |
    | The one /docs entry that isn't content: the REST API reference is
    | generated by Scribe at this same URL (see config/scribe.php's
    | `docs_url`), so it has no markdown file in the content engine. Kept
    | here as a plain link descriptor — the same pattern as
    | services.discord.invite_url — for the /docs hub card and llms.txt.
    |
    */
    'api_reference' => [
        'title' => 'API Reference',
        'url' => '/docs/api',
        'description' => 'REST API documentation for managing CRM entities.',
    ],
];
